### PR TITLE
Avoid runtime calls to promote_op in map

### PR DESCRIPTION
**Pull request by timholy**
This leads to quite a significant performance improvement. On master:

```jl
julia> using StaticArrays
INFO: Recompiling stale cache file /home/tim/.julia/lib/v0.6/StaticArrays.ji for module StaticArrays.

julia> v = @SVector randn(5)
5-element StaticArrays.SVector{5,Float64}:
 -0.284241 
  1.05332  
  0.600952 
 -0.800885 
 -0.0589993

julia> map(abs, v)
5-element StaticArrays.SVector{5,Float64}:
 0.284241 
 1.05332  
 0.600952 
 0.800885 
 0.0589993

julia> using BenchmarkTools

julia> @benchmark map(abs, $v)
BenchmarkTools.Trial: 
  samples:          10000
  evals/sample:     7
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  496.00 bytes
  allocs estimate:  13
  minimum time:     4.62 μs (0.00% GC)
  median time:      4.98 μs (0.00% GC)
  mean time:        5.02 μs (0.74% GC)
  maximum time:     381.92 μs (96.92% GC)

julia> A = @SMatrix rand(3,3); B = @SMatrix rand(3,3);

julia> map(+, A, B)
3×3 StaticArrays.SMatrix{3,3,Float64,9}:
 1.08779   0.696343  1.09782 
 0.327816  0.912551  0.785062
 0.631898  1.23962   1.00753 

julia> @benchmark map(+, $A, $B)
BenchmarkTools.Trial: 
  samples:          10000
  evals/sample:     7
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  496.00 bytes
  allocs estimate:  13
  minimum time:     4.97 μs (0.00% GC)
  median time:      5.20 μs (0.00% GC)
  mean time:        5.35 μs (0.73% GC)
  maximum time:     404.28 μs (96.51% GC)
```
whereas on this branch, those two benchmark runs yield
```jl
julia> @benchmark map(abs, $v)
BenchmarkTools.Trial:
  samples:          10000
  evals/sample:     1000
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  0.00 bytes
  allocs estimate:  0
  minimum time:     2.00 ns (0.00% GC)
  median time:      2.00 ns (0.00% GC)
  mean time:        2.01 ns (0.00% GC)
  maximum time:     22.00 ns (0.00% GC)
                                                                                                                                                     
julia> @benchmark map(+, $A, $B)
BenchmarkTools.Trial:
  samples:          10000
  evals/sample:     1000
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  0.00 bytes
  allocs estimate:  0
  minimum time:     2.00 ns (0.00% GC)
  median time:      2.00 ns (0.00% GC)
  mean time:        2.01 ns (0.00% GC)
  maximum time:     13.00 ns (0.00% GC)
```

I *think* that use of `@pure` is OK, but it's always a little scary.

Note also that I was able to get rid of one generated function; I suspect this pattern might be useful more broadly, but I'm not sure.

### CODE REVIEW

**Comment by timholy** [comment]
Bump. It is a 1000x performance improvement, seems possibly worth having :wink:.

**Comment by andyferris** [comment]
Sorry Tim, I'd forgotten about this one!

I think the reason I didn't merge immediate was because I didn't know how `map` behaves on `NTuple{100}`?

**Comment by andyferris** [comment]
Is the problem the lack of an `@inbounds` in my old implementation?

**Comment by andyferris** [comment]
Right, so current release `SVector{100, Int}` beats `NTuple{100, Int}` at `map(+, v1, v2)` by over a factor of 10:

```
julia> using StaticArrays, BenchmarkTools

julia> t = ntuple(i -> i, 100);

julia> v = SVector(t)

julia> map(+, t, t);

julia> map(+, v, v);

julia> @benchmark map(+, t, t)
BenchmarkTools.Trial:
  samples:          10000
  evals/sample:     10
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  1.75 kb
  allocs estimate:  2
  minimum time:     1.88 μs (0.00% GC)
  median time:      1.91 μs (0.00% GC)
  mean time:        2.04 μs (1.76% GC)
  maximum time:     109.41 μs (97.02% GC)

julia> @benchmark map(+, v, v)
BenchmarkTools.Trial:
  samples:          10000
  evals/sample:     947
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  896.00 bytes
  allocs estimate:  1
  minimum time:     102.00 ns (0.00% GC)
  median time:      127.00 ns (0.00% GC)
  mean time:        144.97 ns (9.36% GC)
  maximum time:     1.20 μs (90.13% GC)
```

**Comment by andyferris** [comment]
Furthermore if I use rc3 and StaticArrays master and re-run your original benchmark, I get:

```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-rc3+0 (2016-08-22 23:43 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> using StaticArrays

julia> v = @SVector randn(5)
5-element StaticArrays.SVector{5,Float64}:
  0.476814
  0.727613
 -0.26638
 -0.14881
 -1.69464

julia> map(abs, v)
5-element StaticArrays.SVector{5,Float64}:
 0.476814
 0.727613
 0.26638
 0.14881
 1.69464

julia> using BenchmarkTools

julia> @benchmark map(abs, $v)
BenchmarkTools.Trial:
  samples:          10000
  evals/sample:     1000
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  0.00 bytes
  allocs estimate:  0
  minimum time:     2.00 ns (0.00% GC)
  median time:      2.00 ns (0.00% GC)
  mean time:        2.02 ns (0.00% GC)
  maximum time:     31.00 ns (0.00% GC)

julia> A = @SMatrix rand(3,3); B = @SMatrix rand(3,3);

julia> map(+, A, B)
3×3 StaticArrays.SMatrix{3,3,Float64,9}:
 0.976043  1.0935    1.41447
 1.51643   1.3758    0.515983
 1.64158   0.894502  1.34128

julia> @benchmark map(+, $A, $B)
BenchmarkTools.Trial:
  samples:          10000
  evals/sample:     1000
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  0.00 bytes
  allocs estimate:  0
  minimum time:     2.00 ns (0.00% GC)
  median time:      2.00 ns (0.00% GC)
  mean time:        2.06 ns (0.00% GC)
  maximum time:     15.00 ns (0.00% GC)

julia>
```

Would you be able to confirm if you still get the 5 microsecond results on your computer?

**Comment by timholy** [comment]
On current master & 0.5.0-rc3, I get 2ns. My guess is that Base added some `@pure` annotations.

Thanks for checking!

**Pull request closed without merging**
